version: '3.1'

services:

  db:
    image: mariadb
    volumes: 
      - ./services/db/data:/var/lib/mysql
    ports:
      - ${SERVICE_DB_PORT}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=workspace

  server:
    build: ./services/server
    volumes: 
      - ../:/app/
      - ${SSH_PATH}:/root/.ssh/
    ports:
      - ${SERVICE_SERVER_PORT}:80
    expose:
      - "9000"
    environment:
      - PHP_DISPLAY_ERRORS=1
      - PHP_DEBUGGER=xdebug
      - WEB_DOCUMENT_ROOT=/app/public
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    volumes:
     - /services/phpmyadmin/sessions
    ports:
     - ${SERVICE_PHPMYADMIN_PORT}:80
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_ROOT_PASSWORD=root
      - PMA_USER=root
      - PMA_PASSWORD=root
      - PMA_PORT=${SERVICE_DB_PORT}
      - PMA_HOST=db
      